name: animeflv
description: An animeflv.net api that allows you to retrieve different data from the animeflv catalog, and use it inside your own app or code using dart.
version: 0.0.7
homepage: https://github.com/raulidg33/animeflv.dart

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  http: ^1.2.2
  html: ^0.15.0
  quiver: ^3.0.1+1
  beautiful_soup_dart: ^0.3.0
  dio: ^5.5.0+1
